Brokers can set status attribute on Inquiries
CraftAcademy/flex_coast_api pull request #8
Opened 2021-06-07 20:09 UTC by christerforsgren91

PT https://www.pivotaltracker.com/story/show/178434414

### User story
```
As a broker
in order to keep track of my clients
I want to be able to change there current status
```

### Changes proposed
- Broker can update inquiries

2021-06-07 20:22 UTC, LucasKnudsen approved these changes

2021-06-07 20:22 UTC, LucasKnudsen commented on spec/requests/api/provider_can_update_inquiry_spec.rb
> +  end
What's the reason that we're sending back the Inquiry? :)

2021-06-07 20:22 UTC, lukeperrin10 requested changes

2021-06-07 20:22 UTC, lukeperrin10 commented on app/controllers/api/inquiries_controller.rb
> +             status: 422
Formatting issue?

2021-06-07 20:22 UTC, lukeperrin10 commented on spec/requests/api/provider_can_update_inquiry_spec.rb
> +end
No sad path?

2021-06-07 20:23 UTC, arunbhalli approved these changes

2021-06-07 20:26 UTC, 1CIM commented on app/controllers/api/inquiries_controller.rb
> +             status: 422
seems like it 🤷‍♂️

2021-06-07 20:27 UTC, 1CIM commented on spec/requests/api/provider_can_update_inquiry_spec.rb
> +end
nope no sad path

2021-06-08 08:34 UTC, lukeperrin10 approved these changes

2021-06-08 08:35 UTC, 1CIM commented on spec/requests/api/provider_can_update_inquiry_spec.rb
> +end
now it dose

2021-06-08 08:36 UTC, merged

2021-06-08 08:41 UTC, oliverochman requested changes

2021-06-08 08:41 UTC, oliverochman commented on app/controllers/api/inquiries_controller.rb
> +    update_inquiry = inquiry.update(inquiry_status: params[:form_data][:inquiry_status])
why do u save this in an variable?

2021-06-08 08:41 UTC, oliverochman commented on db/migrate/20210607182009_add_status_to_inquiries.rb
> +    add_column :inquiries, :inquiry_status, :integer
you should have an default value to this enum

2021-06-08 08:41 UTC, oliverochman commented on spec/requests/api/provider_can_update_inquiry_spec.rb
> +  let!(:inquiry) { create(:inquiry, inquiry_status: 'pending') }
unnecessary use of `let!` , you are using the variable in the test